core/urls.py
from django.contrib import admin
from django.urls import path, include
from payment.views import stripe_webhook
import notifications.urls
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView
from payment.views import StripeAccountLinkView, withdrawal


urlpatterns = [
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('images/favicon.ico'))),
    path('admin/', admin.site.urls),
    path('stripe', stripe_webhook, name='stripe_webhook'),
    path('stripe/auth/', StripeAccountLinkView.as_view(), name='stripe-account-link'),
    path('stripe/withdrawal/', withdrawal, name='stripe-withdrawal-link'),
    path('', include('job.urls', namespace='job')),
    path('', include('user.urls')),
    path('', include('chat.urls')),
    path('', include('payment.urls')),
    path('accounts/', include('allauth.urls')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('blog/', include('blog.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
]

job/urls.py
from django.urls import path
from .views import HomeView, JobCreateView, JobListView, JobDetail, UserListView, ContactView, JobUpdateView, JobDeleteView, HomeSearch

app_name = 'job'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('job/new/', JobCreateView.as_view(), name='job-create'),
    path('job/update/<int:pk>', JobUpdateView.as_view(), name='job-update'),
    path('job/delete/<int:pk>', JobDeleteView.as_view(), name='job-delete'),
    path('job/list/', JobListView.as_view(), name='job-list'),
    path('job/<int:pk>/', JobDetail, name='job-detail'),
    path('freelancers', UserListView.as_view(), name='freelancer'),
    path('contact/', ContactView.as_view(), name='contact' ),
    path('search', HomeSearch.as_view(), name='home-search'),
  
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>

<!-- Basic Page Needs
================================================== -->
<title>Studera- Get your projects done in no time!</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

<!-- CSS
================================================== -->
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="{% static 'css/colors/blue.css' %}">
<link rel="icon"href="{% static 'images/favicon.ico' %}">

</head>
<body>
<!-- Wrapper -->
<div id="wrapper">


    <!-- Header Container
    ================================================== -->
    <header id="header-container" class="fullwidth">
    
        <!-- Header -->
       {% include 'navbar.html' %}
        <!-- Header / End -->
       {% include 'messages.html' %}
       
    </header>
    <div class="clearfix"></div>
    {% block content %}{% endblock content %}
    <!-- Header Container / End -->

<!-- Footer
================================================== -->
{% include 'footer.html' %}
<!-- Footer / End -->

</div>
<!-- Wrapper / End -->

<!-- Scripts
================================================== -->
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/jquery-migrate-3.0.0.min.js' %}"></script>
<script src="{% static 'js/mmenu.min.js' %}"></script>
<script src="{% static 'js/tippy.all.min.js' %}"></script>
<script src="{% static 'js/simplebar.min.js' %}"></script>
<script src="{% static 'js/bootstrap-slider.min.js' %}"></script>
<script src="{% static 'js/bootstrap-select.min.js' %}"></script>
<script src="{% static 'js/snackbar.js' %}"></script>
<script src="{% static 'js/clipboard.min.js' %}"></script>
<script src="{% static 'js/counterup.min.js' %}"></script>
<script src="{% static 'js/magnific-popup.min.js' %}"></script>
<script src="{% static 'js/slick.min.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script>

{% block javascript %}{% endblock javascript%}

{% block inline_javascript %}{% endblock inline_javascript %}

<!-- Snackbar // documentation: https://www.polonel.com/snackbar/ -->
<script>
    
// Snackbar for user status switcher
$('#snackbar-user-status label').click(function() { 
	Snackbar.show({
		text: 'Your status has been changed!',
		pos: 'bottom-center',
		showAction: false,
		actionText: "Dismiss",
		duration: 3000,
		textColor: '#fff',
		backgroundColor: '#383838'
	}); 
}); 
</script>

</body>
</html>

 

 

templates/footer.html
{% load static %}
<div id="footer">
	
	<!-- Footer Top Section -->
	<div class="footer-top-section">
		<div class="container">
			<div class="row">
				<div class="col-xl-12">

					<!-- Footer Rows Container -->
					<div class="footer-rows-container">
						
						<!-- Left Side -->
						<div class="footer-rows-left">
							<div class="footer-row">
								<div class="footer-row-inner footer-logo">
									<img src="{% static 'images/logo2.png' %}" alt="">
								</div>
							</div>
						</div>
						
						<!-- Right Side -->
						<div class="footer-rows-right">

							<!-- Social Icons -->
							<div class="footer-row">
								<div class="footer-row-inner">
									<ul class="footer-social-links">
										<li>
											<a href="#" title="Facebook" data-tippy-placement="bottom" data-tippy-theme="light">
												<i class="icon-brand-facebook-f"></i>
											</a>
										</li>
										<li>
											<a href="#" title="Twitter" data-tippy-placement="bottom" data-tippy-theme="light">
												<i class="icon-brand-twitter"></i>
											</a>
										</li>
										<li>
											<a href="#" title="Google Plus" data-tippy-placement="bottom" data-tippy-theme="light">
												<i class="icon-brand-google-plus-g"></i>
											</a>
										</li>
										<li>
											<a href="#" title="LinkedIn" data-tippy-placement="bottom" data-tippy-theme="light">
												<i class="icon-brand-linkedin-in"></i>
											</a>
										</li>
									</ul>
									<div class="clearfix"></div>
								</div>
							</div>
							
							<!-- Language Switcher -->
							<div class="footer-row">
								<div class="footer-row-inner">
									<select class="selectpicker language-switcher" data-selected-text-format="count" data-size="5">
										<option selected>English</option>
										
									</select>
								</div>
							</div>
						</div>

					</div>
					<!-- Footer Rows Container / End -->
				</div>
			</div>
		</div>
	</div>
	<!-- Footer Top Section / End -->

	<!-- Footer Middle Section -->
	<div class="footer-middle-section">
		<div class="container">
			<div class="row">

				<!-- Links -->
				<div class="col-xl-2 col-lg-2 col-md-3">
					<div class="footer-links">
						<h3>For Candidates</h3>
						<ul>
							<li><a href="{% url 'job:job-list' %}"><span>Browse Tasks</span></a></li>
							<li><a href="{% url 'profile-update' %}"><span>Edit Profile</span></a></li>
							<li><a href="{% url 'my_bids' %}"><span>Manage Bids</span></a></li>
							<li><a href="{% url 'dashboard-favourites' %}"><span>My Favourites</span></a></li>
						</ul>
					</div>
				</div>

				<!-- Links -->
				<div class="col-xl-2 col-lg-2 col-md-3">
					<div class="footer-links">
						<h3>For Employers</h3>
						<ul>
							<li><a href="{% url 'job:freelancer' %}"><span>Browse Freelancers</span></a></li>
							<li><a href="{% url 'dashboard-task' %}"><span>Manage Tasks</span></a></li>
							<li><a href="{% url 'job:job-create' %}"><span>Post a Task</span></a></li>
							
						</ul>
					</div>
				</div>

				<!-- Links -->
				<div class="col-xl-2 col-lg-2 col-md-3">
					<div class="footer-links">
						<h3>Helpful Links</h3>
						<ul>
							<li><a href="{% url 'job:contact' %}"><span>Contact</span></a></li>
							<li><a href="#"><span>Privacy Policy</span></a></li>
							<li><a href="#"><span>Terms of Use</span></a></li>
						</ul>
					</div>
				</div>

				<!-- Links -->
				<div class="col-xl-2 col-lg-2 col-md-3">
					<div class="footer-links">
						<h3>Account</h3>
						<ul>
							<li><a href="{% url 'account_login' %}"><span>Log In</span></a></li>
							<li><a href="{% url 'dashboard' %}"><span>Dashboard</span></a></li>
						</ul>
					</div>
				</div>

				<!-- Newsletter -->
				<div class="col-xl-4 col-lg-4 col-md-12">
					<h3><i class="icon-feather-mail"></i> Sign Up For a Newsletter</h3>
					<p>Weekly breaking news, analysis and cutting edge advices on job searching.</p>
					<form action="#" method="get" class="newsletter">
						<input type="text" name="fname" placeholder="Enter your email address">
						<button type="submit"><i class="icon-feather-arrow-right"></i></button>
					</form>
				</div>
			</div>
		</div>
	</div>
	<!-- Footer Middle Section / End -->
	
	<!-- Footer Copyrights -->
	<div class="footer-bottom-section">
		<div class="container">
			<div class="row">
				<div class="col-xl-12">
					© 2023 <strong>Studera</strong>. All Rights Reserved.
				</div>
			</div>
		</div>
	</div>
	<!-- Footer Copyrights / End -->

</div>

templates/messages.html
{% if messages %}
    {% for message in messages %}

    <div class="notification notice closeable">
        <p>{{ message }}</p>
        <a class="close" href="#"></a>
    </div>
    {% endfor %}
{% endif %}

templates/navbar.html
{% load static %}
{% load notifications_tags %}
{% load notice_extras_tags %}
<div id="header">
    <div class="container">
        
        <!-- Left Side Content -->
        <div class="left-side">
            
            <!-- Logo -->
            <div id="logo">
                <a href="{% url 'job:home' %}"><img src="{% static 'images/logo.png' %}" alt=""></a>
            </div>

            <!-- Main Navigation -->
            <nav id="navigation">
                <ul id="responsive">

                    <li><a href="{% url 'job:home' %}">Home</a>
                       
                    </li>

                    <li><a href="{% url 'job:job-list' %}">Tasks</a></li>

                    <li><a href="{% url 'job:freelancer' %}">Freelancers</a></li>

                    {% if user.is_authenticated %}
                <li><a href="#">Dashboard</a>
                    <ul class="dropdown-nav">
                        <li><a href="{% url 'dashboard' %}">Dashboard</a></li>
                        <li><a href="{% url 'dashboard-messages' %}">Messages</a></li>
                        <li><a href="{% url 'dashboard-favourites' %}">Favourites</a></li>
                        <li><a href="{% url 'reviews' user.id %}">Reviews</a></li>
                        
                        <li><a href="#">Tasks</a>
                            <ul class="dropdown-nav">
                                <li><a href="{% url 'dashboard-task' %}">Manage Tasks</a></li>
                                <li><a href="dashboard-manage-bidders.html">Manage Bidders</a></li>
                                <li><a href="dashboard-my-active-bids.html">My Active Bids</a></li>
                                <li><a href="{% url 'job:job-create' %}">Post a Task</a></li>
                            </ul>
                        </li>
                        <li><a href="{% url 'profile-update' %}">Settings</a></li>
                    </ul>
                </li>
                {% endif %}

                {% comment %} <li><a href="{% url 'blog-home' %}">Blog</a></li> {% endcomment %}
                <li><a href="{% url 'job:contact' %}">Contact Us</a></li>

                </ul>
            </nav>
            <div class="clearfix"></div>
            <!-- Main Navigation / End -->
            
        </div>
        <!-- Left Side Content / End -->


        <!-- Right Side Content / Start -->
    {% if user.is_authenticated %}
    <div class="right-side">
        <!--  User Notifications -->
        <div class="header-widget hide-on-mobile">
            
            <!-- Notifications -->
            <div class="header-notifications">

                <!-- Trigger -->
                <div class="header-notifications-trigger">
                    <a href="#"><i class="icon-feather-bell"></i><span>{{ request|notice_count }}</span></a>
                </div>

                <!-- Dropdown -->
                <div class="header-notifications-dropdown">

                    <div class="header-notifications-headline">
                        <h4>Notifications</h4>
                        <button class="mark-as-read ripple-effect-dark" title="Mark all as read" data-tippy-placement="left">
                            <i class="icon-feather-check-square"></i>
                        </button>
                    </div>

                    <div class="header-notifications-content">
                        <div class="header-notifications-scroll" data-simplebar>
                            <ul>
                                {% for notification in  user.notifications.unread %}
                                <!-- Notification -->
                                {% comment %} <li class="notifications-not-read">
                                    <a href="dashboard-manage-candidates.html">
                                        <span class="notification-icon"><i class="icon-material-outline-group"></i></span>
                                        <span class="notification-text">
                                            <strong>Michael Shannah</strong> applied for a job <span class="color">Full Stack Software Engineer</span>
                                        </span>
                                    </a>
                                </li> {% endcomment %}

                                <!-- Notification -->
                                {% if notification.verb == "application for bid" %}
                                <li>
                                    <a href="dashboard-manage-bidders.html">
                                        <span class="notification-icon"><i class=" icon-material-outline-gavel"></i></span>
                                        <span class="notification-text">
                                            <strong>{{ notification.actor }}</strong> placed a bid on your  <span class="color">{{ notification.description }}</span> project
                                        </span>
                                    </a>
                                </li>
                                {% endif %}

                                <!-- Notification -->
                                {% comment %} <li>
                                    <a href="dashboard-manage-jobs.html">
                                        <span class="notification-icon"><i class="icon-material-outline-autorenew"></i></span>
                                        <span class="notification-text">
                                            Your job listing <span class="color">Full Stack PHP Developer</span> is expiring.
                                        </span>
                                    </a>
                                </li> {% endcomment %}

                                <!-- Notification -->
                                {% comment %} <li>
                                    <a href="dashboard-manage-candidates.html">
                                        <span class="notification-icon"><i class="icon-material-outline-group"></i></span>
                                        <span class="notification-text">
                                            <strong>Sindy Forrest</strong> applied for a job <span class="color">Full Stack Software Engineer</span>
                                        </span>
                                    </a>
                                </li> {% endcomment %}
                                {% endfor %}
                            </ul>
                        </div>
                    </div>

                </div>

            </div>
            
            <!-- Messages -->
            <div class="header-notifications">
                <div class="header-notifications-trigger">
                    <a href="#"><i class="icon-feather-mail"></i><span>{% notifications_unread %}</span></a>
                </div>

                <!-- Dropdown -->
                <div class="header-notifications-dropdown">

                    <div class="header-notifications-headline">
                        <h4>Messages</h4>
                        <button class="mark-as-read ripple-effect-dark" title="Mark all as read" data-tippy-placement="left">
                            <i class="icon-feather-check-square"></i>
                        </button>
                    </div>

                    <div class="header-notifications-content">
                        <div class="header-notifications-scroll" data-simplebar>
                            <ul>
                                <!-- Notification -->
                                {% for notification in  user.notifications.unread %}
                                {% if notification.verb == "messages" %}
                                <li class="notifications-not-read">
                                    <a href="dashboard-messages.html">
                                        <span class="notification-avatar status-online"><img src="{{ notification.actor.profile.image.url }}" alt=""></span>
                                        <div class="notification-text">
                                            <strong>{{ notification.actor }}</strong>
                                            <p class="notification-msg-text">{{ notification.description }}</p>
                                            <span class="color">{{ notification.timestamp }}</span>
                                        </div>
                                    </a>
                                </li>
                                {% endif %}
                                {% endfor %}
                            </ul>
                        </div>
                    </div>

                    <a href="dashboard-messages.html" class="header-notifications-button ripple-effect button-sliding-icon">View All Messages<i class="icon-material-outline-arrow-right-alt"></i></a>
                </div>
            </div>

        </div>
        <!--  User Notifications / End -->

        <!-- User Menu -->
        <div class="header-widget">

            <!-- Messages -->
            <div class="header-notifications user-menu">
                <div class="header-notifications-trigger">
                    <a href="#"><div class="user-avatar status-online"><img src="{{ user.profile.image.url }}" alt=""></div></a>
                </div>

                <!-- Dropdown -->
                <div class="header-notifications-dropdown">

                    <!-- User Status -->
                    <div class="user-status">

                        <!-- User Name / Avatar -->
                        <div class="user-details">
                            <div class="user-avatar status-online"><img src="{{ user.profile.image.url }}" alt=""></div>
                            <div class="user-name">
                                {{user.first_name}}  {{ user.last_name }}
                            </div>
                        </div>
                        
                        <!-- User Status Switcher -->
                        <div class="status-switch" id="snackbar-user-status">
                            <label class="user-online current-status">Online</label>
                            <label class="user-invisible">Invisible</label>
                            <!-- Status Indicator -->
                            <span class="status-indicator" aria-hidden="true"></span>
                        </div>	
                </div>
                
                <ul class="user-menu-small-nav">
                    <li><a href="{% url 'dashboard' %}"><i class="icon-material-outline-dashboard"></i> Dashboard</a></li>
                    <li><a href="#"><i class="icon-material-outline-settings"></i> Settings</a></li>
                    <li><a href="{% url 'account_logout' %}"><i class="icon-material-outline-power-settings-new"></i> Logout</a></li>
                </ul>

                </div>
            </div>

        </div>
        <!-- User Menu / End -->

        <!-- Mobile Navigation Button -->
        <span class="mmenu-trigger">
            <button class="hamburger hamburger--collapse" type="button">
                <span class="hamburger-box">
                    <span class="hamburger-inner"></span>
                </span>
            </button>
        </span>

    </div>
    {% else %}
    
        <!-- Right Side Content / End -->
			<div class="right-side">

				<div class="header-widget">
					<a href="{% url 'account_login' %}" class="log-in-button"><i class="icon-feather-log-in"></i> <span>Log In / Register</span></a>
				</div>

				<!-- Mobile Navigation Button -->
				<span class="mmenu-trigger">
					<button class="hamburger hamburger--collapse" type="button">
						<span class="hamburger-box">
							<span class="hamburger-inner"></span>
						</span>
					</button>
				</span>

			</div>
			<!-- Right Side Content / End -->

        
    {% endif %}
    <!-- Right Side Content / End -->

    </div>
</div>

templates/pagination.html
<div class="pagination">
    <span class="step-links">
    {% if page.has_previous %}
    <a href="?page={{ page.previous_page_number }}">Prev</a>
    {% endif %}
    <span class="current">
    Page {{ page.number }} of {{ page.paginator.num_pages }}.
    </span>
    {% if page.has_next %}
    <a href="?page={{ page.next_page_number }}">Next</a>
    {% endif %}
    </span>
</div>