core/urls.py
from django.contrib import admin
from django.urls import path, include
from payment.views import stripe_webhook
import notifications.urls
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView
from payment.views import StripeAccountLinkView, withdrawal


urlpatterns = [
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('images/favicon.ico'))),
    path('admin/', admin.site.urls),
    path('stripe', stripe_webhook, name='stripe_webhook'),
    path('stripe/auth/', StripeAccountLinkView.as_view(), name='stripe-account-link'),
    path('stripe/withdrawal/', withdrawal, name='stripe-withdrawal-link'),
    path('', include('job.urls', namespace='job')),
    path('', include('user.urls')),
    path('', include('chat.urls')),
    path('', include('payment.urls')),
    path('accounts/', include('allauth.urls')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('blog/', include('blog.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
]

job/urls.py
from django.urls import path
from .views import HomeView, JobCreateView, JobListView, JobDetail, UserListView, ContactView, JobUpdateView, JobDeleteView, HomeSearch

app_name = 'job'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('job/new/', JobCreateView.as_view(), name='job-create'),
    path('job/update/<int:pk>', JobUpdateView.as_view(), name='job-update'),
    path('job/delete/<int:pk>', JobDeleteView.as_view(), name='job-delete'),
    path('job/list/', JobListView.as_view(), name='job-list'),
    path('job/<int:pk>/', JobDetail, name='job-detail'),
    path('freelancers', UserListView.as_view(), name='freelancer'),
    path('contact/', ContactView.as_view(), name='contact' ),
    path('search', HomeSearch.as_view(), name='home-search'),
  
]

user/urls.py
from email import message
from pyexpat.errors import messages
from django.urls import path
from .views import UserDashboard, profile, profileUpdate, Reviews, UserTaskList, dashboard_bidders, dashboard_mybids, bid_update, manage_offer,UserFavourites, BidPaymentView, UserLibraryView, review, message, CreateTestimonial, accept_payment, FundsWithdrawalView, calculate_withdrawal
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
   
    path('profile/<int:id>', profile, name='profile'),
    path('managebidders/job/<int:id>', dashboard_bidders, name='manage-bidders'),
    path('favourites/', UserFavourites.as_view(), name='dashboard-favourites'),
    path('my_bids/', dashboard_mybids, name='my_bids'),
    path('bid_update/<int:id>', bid_update, name='bid_update'),
    path('bid_detail/<int:id>', manage_offer, name='bid_detail'),
    path('dashboard/', UserDashboard, name='dashboard'),
    path('library/', UserLibraryView.as_view(), name='library'),
    path('dashboard/task', UserTaskList.as_view(), name='dashboard-task'),
    path('reviews/<int:user_id>', Reviews.as_view(), name='reviews'),
    path('review/<int:review_id>', review, name='review-details'),
    path('bid_payment/<int:pk>', BidPaymentView.as_view(), name='bid_payment'),
    path('profile_update/', profileUpdate, name='profile-update'),
    path('contact-user/', message, name='contact-user'),
    path('appreview/', CreateTestimonial.as_view(), name='app-review'),
    path('confirm_work/<int:pk>', accept_payment, name='confirm-work'),
    path('withdraw/<int:pk>', FundsWithdrawalView.as_view(), name='withdaw-funds'),
    path('calculate_withdrawal', calculate_withdrawal, name='calculate_withdrawal')
   
    
    
]

if settings.DEBUG:
    urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile, UserNotes, Testimonial

class UserRegistrationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(UserRegistrationForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'submit-field with-border'
    class Meta:
        model = User
        fields = ['username','first_name', 'last_name', 'email', 'password1', 'password2']
        labels = {
            'username':'Enter your username',
            'first_name':'Enter your first name',
            'last_name':'Enter your last name',
            'email':'Enter your email address',
            'password1':'Enter your password',
            'password2':'Repeat your password'
        }
        

class UserUpdateForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(UserUpdateForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'submit-field with-border'
    class Meta:
        model = User
        fields = ['first_name','username', 'last_name', 'email']

class ProfileUpdateForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ProfileUpdateForm, self).__init__(*args, **kwargs)
        self.fields['image'].widget.attrs.update({'class': 'col-auto'})
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'submit-field with-border'
    class Meta:
        model = Profile
        fields = ['image', 'bio', 'tagline']
        labels = {
            'image':'',
        }
       
class UserNotesForm(forms.ModelForm):
    class Meta:
        model = UserNotes
        fields = ['description', 'Priority']

class TestimonialForm(forms.ModelForm):
    class Meta:
        model = Testimonial
        fields = ['testimony']

user/views.py
import json
import stripe
from django.conf import settings
from django.shortcuts import render, redirect, get_object_or_404
from .forms import UserUpdateForm, ProfileUpdateForm, UserNotesForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.base import View, TemplateResponseMixin
from django.contrib import messages
from django.db.models import Avg
from job.models import Job, Bid
from job.forms import BidForm
from django.conf import settings
from django.views import generic
from django.contrib.auth.models import User
from django.http import JsonResponse, HttpResponseRedirect, HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from itertools import chain
from .models import Review, Profile, UserNotes, Testimonial, TrackedProfile, UserWallet
from notifications import notify
from chat.models import Thread, ChatMessage
from django.db.models import Count

stripe.api_key = settings.STRIPE_SECRET_KEY


@login_required
def UserDashboard(request):
    form = UserNotesForm()
    notes = UserNotes.objects.filter(author=request.user)
    wallet = UserWallet.objects.get(owner=request.user)
    bids = Bid.objects.filter(user=request.user)
    count = bids.count()
    reviews_count = Review.objects.filter(freelancer__user=request.user).count()
    views_count = TrackedProfile.objects.filter(profile__user=request.user).count()
    # profile_views = Profile.objects.annotate(num_views=Count('viewers'))

    if request.method == 'POST':
        form = UserNotesForm(request.POST)
        if form.is_valid():
            form.instance.author = request.user
            form.save()
            return redirect('dashboard')
        else:
            form = UserNotesForm()
    # if request.user.is_authenticated:
    #     created = Profile.viewers.through.objects.get_or_create(
    #         profile = object,
    #         user = request.user
    #     )
    #     if created:
    #         object.num_views += 1
    context = {
        'form':form,
        'notes':notes,
        'count':count,
        'reviews_count':reviews_count,
        'views_count': views_count,
        'wallet':wallet
    }

    return render(request, 'user/userdashboard.html', context)
    


class UserTaskList(LoginRequiredMixin, generic.ListView):
    template_name = 'user/task_list.html'

    def get_queryset(self):
        return Job.objects.filter(author=self.request.user)

    def get_context_data(self, **kwargs):
       context =  super(UserTaskList, self).get_context_data(**kwargs)
       job = Job.objects.filter(author = self.request.user)
       count = job.count()
       context.update({
            "count":count
       })

       return context

class UserFavourites(LoginRequiredMixin, generic.ListView):
    template_name = 'user/favourites.html'
    context_object_name = "tasks"
    
    def get_queryset(self):
        return Job.objects.all()

    def get_context_data(self, **kwargs):
        context =  super(UserFavourites, self).get_context_data(**kwargs)
        users = User.objects.all()
        context.update({
            'users':users
        })
        return context
        


@login_required
def profile(request, id):
    users = User.objects.annotate(rating=(Avg('profile__freelancer_review__rating') \
        + Avg('profile__employer_review__rating'))/2).filter(id=id)
    profile = Profile.objects.get(user__id=id)
    reviews = Review.objects.filter(freelancer__user__id=id)
    if request.method == 'POST':
        current_user = request.user
        data = request.POST
        action = data.get('bookmark')
        if action == 'bookmark':
            current_user.profile.favourite.add(users)
        elif action == 'bookmarked':
            current_user.profile.favourite.remove(users)
        current_user.save()
        return redirect('profile', id)
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[-1].strip()
    else:
        ip = request.META.get('REMOTE_ADDR')
    tracked_profile, created = TrackedProfile.objects.get_or_create(
        profile=profile, ip=ip, user=request.user)
    if created:
        tracked_profile.profile.save()
    # account = stripe.Account.retrieve(request.user.stripe_account_id)
    # details_submitted = account["details_submitted"]
    context={
        'users':users,
        'profile':profile,
        'reviews':reviews,
        # 'details_submitted': details_submitted
    }
    return render(request, 'user/profile.html', context)


@login_required
def profileUpdate(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST,instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)

        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('dashboard')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)
        

    context = {
        'u_form':u_form,
        'p_form':p_form
    }
    return render(request, 'user/profile_update.html', context)



@login_required
def dashboard_bidders(request, id):
    
    jobs = Job.objects.filter(id=id)
    job = Job.objects.get(id=id)
    bids = Bid.objects.filter(job__in=jobs)
    bid_count = bids.count()
    
    context = {
        'job':job,
        'bids':bids,
        'bid_count':bid_count,
        'STRIPE_PUBLIC_KEY': settings.STRIPE_PUBLIC_KEY
    }
    return render(request, 'user/manage_bidders.html', context)

@login_required
def dashboard_mybids(request):
    current_user = request.user
    bids = Bid.objects.filter(user=current_user)
    
    form = BidForm()
    
    
    context = {
        'bids':bids,
        'form':form
    }
    return render(request, 'user/my_bids.html', context)

@login_required
def bid_update(request, id):
    current_user = request.user
    bid = Bid.objects.get(id=id)
    
    form = BidForm(instance=bid)
    
    if request.method == 'POST':
        form = BidForm(request.POST, instance=bid)
        if form.is_valid():
            form.save()
            return redirect('my_bids')
    context = {
        'bid':bid,
        'form':form
    }
    return render(request, 'user/bid_update.html', context)


@login_required
def manage_offer(request, id):
    bid = Bid.objects.get(id=id)
    
    context = {
        'bid':bid,
        "STRIPE_PUBLIC_KEY": settings.STRIPE_PUBLIC_KEY
    }
    return render(request, 'user/manage_offer.html', context)


class BidPaymentView(LoginRequiredMixin, generic.DetailView):
    model = Bid
    template_name = 'user/bid_payment.html'
    context_object_name = 'bid'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            "STRIPE_PUBLIC_KEY": settings.STRIPE_PUBLIC_KEY
        })

        return context

class FundsWithdrawalView(LoginRequiredMixin, generic.DetailView):
    model = UserWallet
    template_name = 'payment/withdrawal.html'
    context_object_name = 'wallet'
    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        available_funds = self.request.user.userwallet.amount
        context["available_funds"] = available_funds
        context["service_charge"] = 0
        context["amount_withdrawable"] = 0
        return context
    

@require_http_methods(['POST'])
def calculate_withdrawal(request):
    available_funds = request.user.userwallet.amount
    warning = "Insufficient Funds"
    amount = int(request.POST['amount'])
    if amount <= 0 :
        return render(request, 'payment/withdrawal_summary.html', {'available_funds':available_funds, 'service_charge':0, 'amount_withdrawable':0})
    if amount > available_funds:
        return render(request, 'payment/withdrawal_summary.html', {'available_funds':available_funds, 'service_charge':0, 'amount_withdrawable':0, 'warning':warning})
    if amount > 0 and available_funds > amount:
        service_charge = 0.1 * amount
        amount_withdrawable = amount - service_charge
        return render(request, 'payment/withdrawal_summary.html', {'available_funds':available_funds, 'service_charge':service_charge, 'amount_withdrawable':amount_withdrawable})
    

class UserLibraryView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'user/task_library.html'

def accept_payment(request, pk):
    bid = Bid.objects.get(pk=pk)
    bid.has_paid = True
    bid.status = True
    bid.save()
    bid.user.userwallet.amount += 0.9 * (bid.Amount)
    bid.user.userwallet.save()
    
    return redirect('library')
   

def message(request):
    try:
        if request.method == 'POST':
            sender = User.objects.get(username=request.user)
            receiver = User.objects.get(id=request.POST.get('user_id'))
            notify.send(sender, recipient=receiver, verb='Message', description=request.POST.get('textarea'))
            new_thread, created = Thread.objects.get_or_create(first_person=sender, second_person=receiver)
            ChatMessage.objects.get_or_create(thread=new_thread,user=sender,message=request.POST.get('textarea'))

            return redirect('dashboard-messages')
        else:
            return HttpResponse("Invalid request")
    except Exception as e:
        print(e)
        return HttpResponse("You are not authenticated")


class Reviews(LoginRequiredMixin, TemplateResponseMixin, View):
    template_name = 'user/reviews.html'
    user = None

    def dispatch(self, request, user_id):
        self.user = get_object_or_404(User, id=int(user_id))
        return super(Reviews, self).dispatch(request,user_id )

templates/user/bid_payment.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<div class="clearfix"></div>
<!-- Header Container / End -->

<!-- Titlebar
================================================== -->
<div id="titlebar" class="gradient">
	<div class="container">
		<div class="row">
			<div class="col-md-12">

				<h2>Checkout</h2>

				<!-- Breadcrumbs -->
				<nav id="breadcrumbs" class="dark">
					<ul>
						<li><a href="#">Home</a></li>
						<li><a href="#">Pricing Plans</a></li>
						<li>Checkout</li>
					</ul>
				</nav>

			</div>
		</div>
	</div>
</div>

<!-- Content
================================================== -->
<!-- Container -->
<div class="container">
	<div class="row">
		<div class="col-xl-8 col-lg-8 content-right-offset">
			
			<!-- Hedline -->
			<h3>Payment Method</h3>

			<!-- Payment Methods Accordion -->
			<div class="payment margin-top-30">

				<div class="payment-tab">
					<div class="payment-tab-trigger">
						<input checked id="paypal" name="cardType" type="radio" value="paypal">
						<label for="paypal">PayPal</label>
						<img class="payment-logo paypal" src="https://i.imgur.com/ApBxkXU.png" alt="">
					</div>

					<div class="payment-tab-content">
						<p>You will be redirected to PayPal to complete payment.</p>
                        <p><a href="pages-order-confirmation.html" class="button big ripple-effect">Continue Payment</a></p>
					</div>
				</div>


				<div class="payment-tab payment-tab-active">
					<div class="payment-tab-trigger">
						<input type="radio" name="cardType" id="creditCart" value="creditCard">
						<label for="creditCart">Credit / Debit Card</label>
						<img class="payment-logo" src="https://i.imgur.com/IHEKLgm.png" alt="">
					</div>
                    <div class="payment-tab-content">
						<p>You will be redirected to Stripe to complete payment.</p>
                        <p><button
							class="margin-top-10 button button-sliding-icon"
							type="submit"
							id="checkout-button">Pay now <i class="icon-material-outline-arrow-right-alt"></i>
							</button></p>
					</div>

					<div class="payment-tab-content">
						<div class="row payment-form-row">

					
						</div>
					</div>
				</div>

			</div>
			<!-- Payment Methods Accordion / End -->
		
			
		</div>


		<!-- Summary -->
		<div class="col-xl-4 col-lg-4 margin-top-0 margin-bottom-60">
			
			<!-- Summary -->
			<div class="boxed-widget summary margin-top-0">
				<div class="boxed-widget-headline">
					<h3>Summary</h3>
				</div>
				<div class="boxed-widget-inner">
					<ul>
						<li>Standard Plan <span>${{ bid.Amount }}</span></li>
						<li>VAT (0%) <span>$0.00</span></li>
						<li class="total-costs">Final Price <span>${{ bid.Amount }}</span></li>
					</ul>
				</div>
			</div>
			<!-- Summary / End -->

			<!-- Checkbox -->
			<div class="checkbox margin-top-30">
				<input type="checkbox" id="two-step">
				<label for="two-step"><span class="checkbox-icon"></span>  I agree to the <a href="#">Terms and Conditions</a> and the <a href="#">Automatic Renewal Terms</a></label>
			</div>
		</div>

	</div>
</div>
<!-- Container / End -->
{% csrf_token %}

<script src="https://js.stripe.com/v3/"></script>
<script type="text/javascript">

	const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
		// Create an instance of the Stripe object with your publishable API key
		var stripe = Stripe("{{ STRIPE_PUBLIC_KEY }}");
		var checkoutButton = document.getElementById("checkout-button");
		checkoutButton.addEventListener("click", function () {
		  fetch("{% url 'create-checkout-session' bid.id %}", {
			method: "POST",
			headers: {
				'X-CSRFToken': csrftoken
			}
		  })
			.then(function (response) {
			  return response.json();
			})
			.then(function (session) {
			  return stripe.redirectToCheckout({ sessionId: session.id });
			})
			.then(function (result) {
			  // If redirectToCheckout fails due to a browser or network
			  // error, you should display the localized error message to your
			  // customer using error.message.
			  if (result.error) {
				alert(result.error.message);
			  }
			})
			.catch(function (error) {
			  console.error("Error:", error);
			});
		});
	
	
	</script>




{% endblock content %}

templates/user/bid_update.html
{% extends 'user/dashboard.html' %}
{% block content %}


	<!-- Dashboard Content
	================================================== -->
	
			
			<!-- Dashboard Headline -->
			<div class="dashboard-headline">
				<h3>My Active Bids</h3>

				<!-- Breadcrumbs -->
				<nav id="breadcrumbs" class="dark">
					<ul>
						<li><a href="#">Home</a></li>
						<li><a href="#">Dashboard</a></li>
						<li>My Active Bids</li>
					</ul>
				</nav>
			</div>
	
			<!-- Row -->
			<div class="row">

				<!-- Dashboard Box -->
				<div class="col-xl-12">
					<div class="dashboard-box margin-top-0">

						<!-- Headline -->
						<div class="headline">
							<h3><i class="icon-material-outline-gavel"></i> Manage your bid on {{ bid.job.title }}</h3>
						</div>

						<div class="content">
							<ul class="dashboard-box-list">
                                
								<li>
									<!-- Job Listing -->
									<div class="job-listing width-adjustment">

										<!-- Job Listing Details -->
										<div class="job-listing-details">

											<!-- Details -->
											<div class="job-listing-description">
												<h3 class="job-listing-title"><a href="#">{{ bid.job.title }}</a></h3>
											</div>
										</div>
									</div>
									
									<!-- Task Details -->
									<ul class="dashboard-task-info">
										<li><strong>${{ bid.Amount }}</strong><span>Hourly Rate</span></li>
										<li><strong>{{ bid.time }} {{ bid.denom }}</strong><span>Delivery Time</span></li>
									</ul>

									<!-- Buttons -->
									<div class="buttons-to-right always-visible">
										<a href="#small-dialog" class="popup-with-zoom-anim button dark ripple-effect ico" title="Edit Bid" data-tippy-placement="top"><i class="icon-feather-edit"></i></a>
										<a href="#" class="button red ripple-effect ico" title="Cancel Bid" data-tippy-placement="top"><i class="icon-feather-trash-2"></i></a>
									</div>
								</li>
								
							</ul>
						</div>
					</div>
				</div>

			</div>
			<!-- Row / End -->

			

		
	<!-- Dashboard Content / End -->




<!-- Wrapper / End -->


<!-- Edit Bid Popup
================================================== -->
<div id="small-dialog" class="zoom-anim-dialog mfp-hide dialog-with-tabs">

	<!--Tabs -->
	<div class="sign-in-form">

		<ul class="popup-tabs-nav">
			<li><a href="#tab">Edit Bid</a></li>
		</ul>

		<div class="popup-tabs-container">

			<!-- Tab -->
			<form action="" method="post">
                {% csrf_token %}
			<div class="popup-tab-content" id="tab">
					
					<!-- Bidding -->
					{{ form }}
				
				<!-- Button -->
				<input class="button full-width button-sliding-icon ripple-effect" type="submit" value="Save Changes">
			</form>
			</div>

		</div>
	</div>
</div>
<!-- Edit Bid Popup / End -->
{% endblock content %}

templates/user/favourites.html
{% extends 'dashboard/base.html' %}
{% block content %}
    <!-- Dashboard Headline -->
			<div class="dashboard-headline">
				<h3>Favourites</h3>

				<!-- Breadcrumbs -->
				<nav id="breadcrumbs" class="dark">
					<ul>
						<li><a href="#">Home</a></li>
						<li><a href="#">Dashboard</a></li>
						<li>Favourites</li>
					</ul>
				</nav>
			</div>
	
			<!-- Row -->
			<div class="row">

				<!-- Dashboard Box -->
				
				<div class="col-xl-12">
					<div class="dashboard-box margin-top-0">

						<!-- Headline -->
						<div class="headline">
							<h3><i class="icon-material-outline-business-center"></i> Favourited Jobs</h3>
						</div>

						<div class="content">
							<ul class="dashboard-box-list">
								{% for task in tasks %}
								{% if user in task.favourite.all %}
								<li>
									<!-- Job Listing -->
									<div class="job-listing">

										<!-- Job Listing Details -->
										<div class="job-listing-details">

											<!-- Logo -->
											<a href="#" class="job-listing-company-logo">
												<img src="{{ task.author.profile.image.url }}" alt="">
											</a>

											<!-- Details -->
											<div class="job-listing-description">
												<h3 class="job-listing-title"><a href="#">{{ task.title }}</a></h3>

												<!-- Job Listing Footer -->
												<div class="job-listing-footer">
													<ul>
														<li><i class="icon-material-outline-access-time"></i> 2 days ago</li>
													</ul>
												</div>
											</div>
										</div>
									</div>
									<!-- Buttons -->
									<div class="buttons-to-right">
										<a href="#" class="button red ripple-effect ico" title="Remove" data-tippy-placement="left"><i class="icon-feather-trash-2"></i></a>
									</div>
								</li>
								{% endif %}
								{% endfor %}

							</ul>
						</div>
					</div>
				</div>

				<!-- Dashboard Box -->
				<div class="col-xl-12">
					<div class="dashboard-box">

						<!-- Headline -->
						<div class="headline">
							<h3><i class="icon-material-outline-face"></i> Favourited Freelancers</h3>
						</div>

						<div class="content">
							<ul class="dashboard-box-list">
								{% for u in users %}
								{% if u in user.profile.favourite.all %}
								<li>
									<!-- Overview -->
									<div class="freelancer-overview">
										<div class="freelancer-overview-inner">

											<!-- Avatar -->
											<div class="freelancer-avatar">
												<div class="verified-badge"></div>
												<a href="#"><img src="{{ u.profile.image.url }}" alt=""></a>
											</div>

											<!-- Name -->
											<div class="freelancer-name">
												<h4><a href="#">{{u.first_name}} {{ u.last_name }} </a></h4>
												<span>{{ u.profile.tagline }}</span>
												<!-- Rating -->
												<div class="freelancer-rating">
													<div class="star-rating" data-rating="4.2"></div>
												</div>
											</div>
										</div>
									</div>

									<!-- Buttons -->
									<div class="buttons-to-right">
										<a href="#" class="button red ripple-effect ico" title="Remove" data-tippy-placement="left"><i class="icon-feather-trash-2"></i></a>
									</div>
								</li>
								{% endif %}
								{% endfor %}
								
							</ul>
						</div>
					</div>
				</div>

			</div>
			<!-- Row / End -->
{% endblock content %}

templates/user/task_list.html
{% extends 'dashboard/base.html' %}
{% block content %}

<!-- Row -->
<div class="row">

    <!-- Dashboard Box -->
    <div class="col-xl-12">
        <div class="dashboard-box margin-top-0">

            <!-- Headline -->
            <div class="headline">
                <h3><i class="icon-material-outline-assignment"></i> My Tasks ({{ count }})</h3>
            </div>

            <div class="content">
                <ul class="dashboard-box-list">
                    {% for task in object_list %}
                    <li>
                        <!-- Job Listing -->
                        <div class="job-listing width-adjustment">

                            <!-- Job Listing Details -->
                            <div class="job-listing-details">

                                <!-- Details -->
                                <div class="job-listing-description">
                                    <h3 class="job-listing-title"><a href="#">{{ task.title }}</a> <span class="dashboard-status-button yellow">Expiring</span></h3>

                                    <!-- Job Listing Footer -->
                                    <div class="job-listing-footer">
                                        <ul>
                                            <li><i class="icon-material-outline-access-time"></i> 23 hours left</li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        <!-- Task Details -->
                        <ul class="dashboard-task-info">
                            
                           
                            
                            <li><strong>$22</strong><span>Avg. Bid</span></li>
                            <li><strong>${{ task.cost }}</strong><span>Price</span></li>
                            
                        </ul>

                        <!-- Buttons -->
                        <div class="buttons-to-right always-visible">
                            <a href="{% url 'manage-bidders' task.id %}" class="button ripple-effect"><i class="icon-material-outline-supervisor-account"></i> Manage Bidders </a>
                            <a href="{% url 'job:job-update' task.id %}" class="button gray ripple-effect ico" title="Edit" data-tippy-placement="top"><i class="icon-feather-edit"></i></a>
                            <a href="{% url 'job:job-delete' task.id %}" class="button gray ripple-effect ico" title="Remove" data-tippy-placement="top"><i class="icon-feather-trash-2"></i></a>
                        </div>
                    </li>

                    {% endfor %}

                    

                </ul>
            </div>
        </div>
    </div>

</div>
<!-- Row / End -->


{% endblock content %}